### ISSUE TITLE
build a container in Jenkins that puts the executable into an Alpine based container

### ISSUE THREAD

**Issue by zacsketches** [FATHOM5/to-the-edge#2]

**Comment by BrentFathom5** [comment]
Got this working with the golang:alpine3.11 image. By default, go compiles the binary with dynamically linked libraries, which the alpine image does not like. To fix this, we set the CGO_ENABLED golang environment variable in Jenkins to 0 **before** compiling the golang code. That way, the binary is a TRUE standalone binary with no dynamically linked libraries. This fix has been integrated into Jenkins. Closing this issue.
